In [1]:
# Load libraries
import pandas as pd

In [2]:
# Load dataset and display the first five rows
demo_data = pd.read_csv('demographics_train.csv')
demo_data.head()

,State,County,FIPS,Total Population,Citizen Voting-Age Population,"Percent White, not Hispanic or Latino","Percent Black, not Hispanic or Latino",Percent Hispanic or Latino,Percent Foreign Born,Percent Female,Percent Age 29 and Under,Percent Age 65 and Older,Median Household Income,Percent Unemployed,Percent Less than High School Degree,Percent Less than Bachelor's Degree,Percent Rural
0,Wisconsin,La Crosse,55063,117538,0,90.537528,1.214075,1.724549,2.976059,51.171536,43.241335,14.702479,51477,4.796952,5.474767,67.529757,16.827753
1,Virginia,Alleghany,51005,15919,12705,91.940449,5.207614,1.432251,1.300333,51.077329,31.660280,23.902255,45538,4.560986,15.537543,83.711604,52.393846
2,Indiana,Fountain,18045,16741,12750,95.705155,0.400215,2.359477,1.547100,49.770026,35.899887,18.941521,45924,7.978789,12.032155,85.538940,65.951276
3,Ohio,Geauga,39055,94020,0,95.837056,1.256116,1.294405,2.578175,50.678579,36.281642,18.028079,74165,4.036902,8.928599,62.730824,63.968990
4,Wisconsin,Jackson,55053,20566,15835,86.662453,1.983857,3.082758,1.376058,46.649810,36.292911,17.587280,49608,5.569698,11.792912,86.129256,72.238251

In [7]:
elec_data = pd.read_csv('election_train.csv')
elec_data.head()

   Year State           County      Office       Party  Votes
0  2018    AZ    Apache County  US Senator  Democratic  16298
1  2018    AZ    Apache County  US Senator  Republican   7810
2  2018    AZ   Cochise County  US Senator  Democratic  17383
3  2018    AZ   Cochise County  US Senator  Republican  26929
4  2018    AZ  Coconino County  US Senator  Democratic  34240

In [13]:
elec_data_tidy = pd.pivot_table(elec_data, index=['Year', 'State', 'County', 'Office'], values='Votes', columns='Party').reset_index()
elec_data_tidy.head()
elec_data.description

AttributeError: 'DataFrame' object has no attribute 'description'